"""add finding, evidence, recommendation tables

Revision ID: 012ac35d7a31
Revises: 67e3985cd940
Create Date: 2026-08-27 17:33:39.846450

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op
from radar_core.types import UTCDateTime

# revision identifiers, used by Alembic.
revision = "012ac35d7a31"
down_revision = "67e3985cd940"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "finding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scoring_run_id", sa.Integer(), nullable=False),
        sa.Column("criterion_id", sa.Integer(), nullable=False),
        sa.Column("tool_result_id", sa.Integer(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", name="findingseverity"),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("line", sa.Integer(), nullable=True),
        sa.Column("estimated_effort", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "confidence", sa.Enum("HIGH", "MEDIUM", "LOW", name="confidence"), nullable=False
        ),
        sa.Column(
            "status", sa.Enum("OPEN", "RESOLVED", "WONT_FIX", name="findingstatus"), nullable=False
        ),
        sa.Column(
            "human_verdict",
            sa.Enum("UNREVIEWED", "TRUE_POSITIVE", "FALSE_POSITIVE", name="humanverdict"),
            nullable=False,
        ),
        sa.Column("detected_at", UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["criterion_id"],
            ["criterion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scoring_run_id"],
            ["scoring_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_result_id"],
            ["tool_result.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("finding", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_finding_criterion_id"), ["criterion_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_finding_scoring_run_id"), ["scoring_run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_finding_tool_result_id"), ["tool_result_id"], unique=False
        )

    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("finding_id", sa.Integer(), nullable=True),
        sa.Column("score_id", sa.Integer(), nullable=True),
        sa.Column(
            "evidence_type",
            sa.Enum(
                "TOOL_OUTPUT_EXCERPT",
                "HUMAN_CONFIRMATION",
                "EXTERNAL_REFERENCE",
                name="evidencetype",
            ),
            nullable=False,
        ),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=True),
        sa.CheckConstraint(
            "(finding_id IS NOT NULL) + (score_id IS NOT NULL) = 1",
            name="ck_evidence_exactly_one_parent",
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["finding.id"],
        ),
        sa.ForeignKeyConstraint(
            ["score_id"],
            ["score.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evidence_finding_id"), ["finding_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_score_id"), ["score_id"], unique=False)

    op.create_table(
        "recommendation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("finding_id", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["finding.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recommendation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recommendation_finding_id"), ["finding_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recommendation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendation_finding_id"))

    op.drop_table("recommendation")
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_score_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_finding_id"))

    op.drop_table("evidence")
    with op.batch_alter_table("finding", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_finding_tool_result_id"))
        batch_op.drop_index(batch_op.f("ix_finding_scoring_run_id"))
        batch_op.drop_index(batch_op.f("ix_finding_criterion_id"))

    op.drop_table("finding")
    # ### end Alembic commands ###
