"""add enum check constraints and not null on datetime/json columns

Revision ID: 555ffc592f67
Revises: 84f11b00cd34
Create Date: 2026-08-27 20:34:55.209345

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "555ffc592f67"
down_revision = "84f11b00cd34"
branch_labels = None
depends_on = None

# NOTE: SQLAlchemy's Enum(create_constraint=True) CHECK constraint is
# "type-bound" and is deliberately excluded by Alembic's autogenerate
# comparator (alembic.autogenerate.compare.check_constraints), so it is
# never picked up automatically. The CHECK constraints below were added by
# hand after `alembic revision --autogenerate` produced only the NOT NULL
# column changes.


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit", schema=None) as batch_op:
        batch_op.alter_column(
            "audited_at",
            existing_type=sa.DATETIME(),
            nullable=False,
        )
        batch_op.alter_column(
            "network_flags",
            existing_type=sqlite.JSON(),
            nullable=False,
        )

    with op.batch_alter_table("criterion", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "ck_criterion_scoring_model_valid",
            "scoring_model IN ('FIXED_SCALE', 'STATUS_4STATE')",
        )

    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=False,
        )
        batch_op.create_check_constraint(
            "ck_evidence_evidence_type_valid",
            "evidence_type IN ('TOOL_OUTPUT_EXCERPT', 'HUMAN_CONFIRMATION', 'EXTERNAL_REFERENCE')",
        )

    with op.batch_alter_table("finding", schema=None) as batch_op:
        batch_op.alter_column(
            "detected_at",
            existing_type=sa.DATETIME(),
            nullable=False,
        )
        batch_op.create_check_constraint(
            "ck_finding_severity_valid",
            "severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO')",
        )
        batch_op.create_check_constraint(
            "ck_finding_confidence_valid",
            "confidence IN ('HIGH', 'MEDIUM', 'LOW')",
        )
        batch_op.create_check_constraint(
            "ck_finding_status_valid",
            "status IN ('OPEN', 'RESOLVED', 'WONT_FIX')",
        )
        batch_op.create_check_constraint(
            "ck_finding_human_verdict_valid",
            "human_verdict IN ('UNREVIEWED', 'TRUE_POSITIVE', 'FALSE_POSITIVE')",
        )

    with op.batch_alter_table("improvement_task", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=False,
        )

    with op.batch_alter_table("methodology_version", schema=None) as batch_op:
        batch_op.alter_column(
            "frozen_at",
            existing_type=sa.DATETIME(),
            nullable=False,
        )

    with op.batch_alter_table("recommendation", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=False,
        )

    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=False,
        )

    with op.batch_alter_table("roadmap_item", schema=None) as batch_op:
        batch_op.alter_column(
            "promoted_at",
            existing_type=sa.DATETIME(),
            nullable=False,
        )
        batch_op.create_check_constraint(
            "ck_roadmap_item_status_valid",
            "status IN ('TODO', 'IN_PROGRESS', 'DONE', 'WONT_FIX')",
        )

    with op.batch_alter_table("score", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "ck_score_level_valid",
            "level IN ('CRITERION', 'CATEGORY', 'GLOBAL')",
        )
        batch_op.create_check_constraint(
            "ck_score_confidence_valid",
            "confidence IN ('HIGH', 'MEDIUM', 'LOW')",
        )

    with op.batch_alter_table("scoring_run", schema=None) as batch_op:
        batch_op.alter_column(
            "scored_at",
            existing_type=sa.DATETIME(),
            nullable=False,
        )
        batch_op.create_check_constraint(
            "ck_scoring_run_global_confidence_valid",
            "global_confidence IN ('HIGH', 'MEDIUM', 'LOW')",
        )

    with op.batch_alter_table("snapshot", schema=None) as batch_op:
        batch_op.alter_column(
            "taken_at",
            existing_type=sa.DATETIME(),
            nullable=False,
        )
        batch_op.alter_column(
            "details",
            existing_type=sqlite.JSON(),
            nullable=False,
        )
        batch_op.create_check_constraint(
            "ck_snapshot_portfolio_global_confidence_valid",
            "portfolio_global_confidence IN ('HIGH', 'MEDIUM', 'LOW')",
        )

    with op.batch_alter_table("tool_result", schema=None) as batch_op:
        batch_op.alter_column(
            "raw_output",
            existing_type=sqlite.JSON(),
            nullable=False,
        )
        batch_op.alter_column(
            "ran_at",
            existing_type=sa.DATETIME(),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tool_result", schema=None) as batch_op:
        batch_op.alter_column(
            "ran_at",
            existing_type=sa.DATETIME(),
            nullable=True,
        )
        batch_op.alter_column(
            "raw_output",
            existing_type=sqlite.JSON(),
            nullable=True,
        )

    with op.batch_alter_table("snapshot", schema=None) as batch_op:
        batch_op.drop_constraint("ck_snapshot_portfolio_global_confidence_valid", type_="check")
        batch_op.alter_column(
            "details",
            existing_type=sqlite.JSON(),
            nullable=True,
        )
        batch_op.alter_column(
            "taken_at",
            existing_type=sa.DATETIME(),
            nullable=True,
        )

    with op.batch_alter_table("scoring_run", schema=None) as batch_op:
        batch_op.drop_constraint("ck_scoring_run_global_confidence_valid", type_="check")
        batch_op.alter_column(
            "scored_at",
            existing_type=sa.DATETIME(),
            nullable=True,
        )

    with op.batch_alter_table("score", schema=None) as batch_op:
        batch_op.drop_constraint("ck_score_confidence_valid", type_="check")
        batch_op.drop_constraint("ck_score_level_valid", type_="check")

    with op.batch_alter_table("roadmap_item", schema=None) as batch_op:
        batch_op.drop_constraint("ck_roadmap_item_status_valid", type_="check")
        batch_op.alter_column(
            "promoted_at",
            existing_type=sa.DATETIME(),
            nullable=True,
        )

    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=True,
        )

    with op.batch_alter_table("recommendation", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=True,
        )

    with op.batch_alter_table("methodology_version", schema=None) as batch_op:
        batch_op.alter_column(
            "frozen_at",
            existing_type=sa.DATETIME(),
            nullable=True,
        )

    with op.batch_alter_table("improvement_task", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=True,
        )

    with op.batch_alter_table("finding", schema=None) as batch_op:
        batch_op.drop_constraint("ck_finding_human_verdict_valid", type_="check")
        batch_op.drop_constraint("ck_finding_status_valid", type_="check")
        batch_op.drop_constraint("ck_finding_confidence_valid", type_="check")
        batch_op.drop_constraint("ck_finding_severity_valid", type_="check")
        batch_op.alter_column(
            "detected_at",
            existing_type=sa.DATETIME(),
            nullable=True,
        )

    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_constraint("ck_evidence_evidence_type_valid", type_="check")
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=True,
        )

    with op.batch_alter_table("criterion", schema=None) as batch_op:
        batch_op.drop_constraint("ck_criterion_scoring_model_valid", type_="check")

    with op.batch_alter_table("audit", schema=None) as batch_op:
        batch_op.alter_column(
            "network_flags",
            existing_type=sqlite.JSON(),
            nullable=True,
        )
        batch_op.alter_column(
            "audited_at",
            existing_type=sa.DATETIME(),
            nullable=True,
        )

    # ### end Alembic commands ###
