"""add scoring_run, score tables

Revision ID: 67e3985cd940
Revises: bbe692cddca9
Create Date: 2026-08-27 17:29:46.175676

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from radar_core.types import UTCDateTime


# revision identifiers, used by Alembic.
revision = '67e3985cd940'
down_revision = 'bbe692cddca9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('methodology_version_id', sa.Integer(), nullable=False),
    sa.Column('scored_at', UTCDateTime(), nullable=True),
    sa.Column('global_score', sa.Float(), nullable=True),
    sa.Column('global_confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence'), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit.id'], ),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'methodology_version_id', name='uq_scoringrun_audit_methodology')
    )
    with op.batch_alter_table('scoring_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scoring_run_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scoring_run_methodology_version_id'), ['methodology_version_id'], unique=False)

    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scoring_run_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Enum('CRITERION', 'CATEGORY', 'GLOBAL', name='scorelevel'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence'), nullable=False),
    sa.Column('na_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['criterion_id'], ['criterion.id'], ),
    sa.ForeignKeyConstraint(['scoring_run_id'], ['scoring_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_criterion_id'), ['criterion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_scoring_run_id'), ['scoring_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_scoring_run_id'))
        batch_op.drop_index(batch_op.f('ix_score_criterion_id'))
        batch_op.drop_index(batch_op.f('ix_score_category_id'))

    op.drop_table('score')
    with op.batch_alter_table('scoring_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scoring_run_methodology_version_id'))
        batch_op.drop_index(batch_op.f('ix_scoring_run_audit_id'))

    op.drop_table('scoring_run')
    # ### end Alembic commands ###
