"""add methodology_version, category, criterion tables

Revision ID: 6b426c4d28a1
Revises: 978d1b673fff
Create Date: 2026-08-27 17:20:12.610670

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op
from radar_core.types import UTCDateTime

# revision identifiers, used by Alembic.
revision = "6b426c4d28a1"
down_revision = "978d1b673fff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "methodology_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version_label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("frozen_at", UTCDateTime(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("methodology_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_methodology_version_version_label"), ["version_label"], unique=True
        )

    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("methodology_version_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["methodology_version_id"],
            ["methodology_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_category_methodology_version_id"),
            ["methodology_version_id"],
            unique=False,
        )

    op.create_table(
        "criterion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column(
            "scoring_model",
            sa.Enum("FIXED_SCALE", "STATUS_4STATE", name="scoringmodel"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("criterion", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_criterion_category_id"), ["category_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("criterion", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_criterion_category_id"))

    op.drop_table("criterion")
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_category_methodology_version_id"))

    op.drop_table("category")
    with op.batch_alter_table("methodology_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_methodology_version_version_label"))

    op.drop_table("methodology_version")
    # ### end Alembic commands ###
