"""add snapshot table

Revision ID: 84f11b00cd34
Revises: bc2fd2ee7b41
Create Date: 2026-08-27 17:42:00.624410

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from radar_core.types import UTCDateTime


# revision identifiers, used by Alembic.
revision = '84f11b00cd34'
down_revision = 'bc2fd2ee7b41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taken_at', UTCDateTime(), nullable=True),
    sa.Column('portfolio_global_score', sa.Float(), nullable=False),
    sa.Column('portfolio_global_confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot')
    # ### end Alembic commands ###
