"""add repository table

Revision ID: 978d1b673fff
Revises: f8abd766584c
Create Date: 2026-08-27 17:09:46.676369

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from radar_core.types import UTCDateTime


# revision identifiers, used by Alembic.
revision = '978d1b673fff'
down_revision = 'f8abd766584c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repository_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_name'))

    op.drop_table('repository')
    # ### end Alembic commands ###
