"""add improvement_task, roadmap_item, finding_improvement_task_link tables

Revision ID: bc2fd2ee7b41
Revises: 012ac35d7a31
Create Date: 2026-08-27 17:38:18.992989

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from radar_core.types import UTCDateTime


# revision identifiers, used by Alembic.
revision = 'bc2fd2ee7b41'
down_revision = '012ac35d7a31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('improvement_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finding_improvement_task_link',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('improvement_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.ForeignKeyConstraint(['improvement_task_id'], ['improvement_task.id'], ),
    sa.PrimaryKeyConstraint('finding_id', 'improvement_task_id')
    )
    op.create_table('roadmap_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('improvement_task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'WONT_FIX', name='roadmapstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('estimated_effort', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_impact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('promoted_at', UTCDateTime(), nullable=True),
    sa.Column('done_at', UTCDateTime(), nullable=True),
    sa.Column('done_evidence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['done_evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['improvement_task_id'], ['improvement_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roadmap_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roadmap_item_improvement_task_id'), ['improvement_task_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmap_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roadmap_item_improvement_task_id'))

    op.drop_table('roadmap_item')
    op.drop_table('finding_improvement_task_link')
    op.drop_table('improvement_task')
    # ### end Alembic commands ###
