"""initial empty schema

Revision ID: f8abd766584c
Revises:
Create Date: 2026-08-27 16:58:56.984270

"""

# revision identifiers, used by Alembic.
revision = "f8abd766584c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
